[06:14:37] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[06:14:37] Error: {
  error_code: 901,
  error_msg: "Can't send messages for users without permission",
  request_params: [Array]
}
[06:46:12] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[06:46:12] Error: {
  error_code: 901,
  error_msg: "Can't send messages for users without permission",
  request_params: [Array]
}
[07:14:13] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:14:13] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:14:47] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[07:14:47] Error: {
  error_code: 901,
  error_msg: "Can't send messages for users without permission",
  request_params: [Array]
}
[07:17:09] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:17:09] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:17:42] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:17:42] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:18:28] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[07:18:28] Error: {
  error_code: 901,
  error_msg: "Can't send messages for users without permission",
  request_params: [Array]
}
[07:20:06] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:20:06] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:20:17] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:20:17] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:20:40] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:20:40] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:21:34] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:21:34] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:22:30] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:22:30] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:23:14] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:23:14] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:23:48] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:23:48] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:23:59] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:23:59] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:25:28] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:25:28] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:26:13] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:26:13] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:26:35] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:26:35] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:28:47] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:28:47] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:30:27] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:30:27] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:30:50] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:30:50] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:31:12] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:31:12] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:31:23] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:31:23] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:31:33] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:31:33] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:31:43] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:31:43] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:31:53] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:31:53] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:32:03] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:32:03] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:32:14] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:32:14] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:32:24] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:32:24] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:32:35] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:32:35] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:32:47] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:32:47] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:32:58] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:32:58] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:33:31] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:33:31] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:33:41] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:33:41] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:33:52] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:33:52] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:34:14] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:34:14] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:34:36] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:34:36] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:34:46] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:34:46] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:34:56] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:34:56] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:35:07] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:35:07] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:35:27] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:35:27] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:35:38] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:35:38] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:35:49] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:35:49] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:36:00] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:36:00] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:36:11] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:36:11] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:36:22] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:36:22] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:36:32] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:36:32] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:36:42] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:36:42] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:36:52] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:36:52] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:37:03] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:37:03] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:37:14] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:37:14] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:37:25] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:37:25] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:37:36] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:37:36] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:37:46] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:37:46] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:37:57] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:37:57] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:38:08] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:38:08] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:38:18] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:38:18] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:38:29] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:38:29] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:38:39] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:38:39] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:38:50] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:38:50] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:39:13] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:39:13] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:39:24] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:39:24] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:39:35] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:39:35] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:39:46] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:39:46] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:39:57] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:39:57] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:40:08] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:40:08] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:40:19] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:40:19] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:40:30] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:40:30] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:40:40] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:40:40] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:40:51] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:40:51] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:41:01] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:41:01] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:41:13] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:41:13] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:41:23] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:41:23] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:41:33] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:41:33] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:41:43] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:41:43] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:41:53] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:41:53] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:42:03] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:42:03] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:42:14] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:42:14] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:42:25] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:42:25] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:42:36] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:42:36] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:42:47] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:42:47] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:42:57] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:42:57] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:44:37] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:44:37] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:44:48] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:44:48] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:44:58] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:44:58] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:45:08] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:45:08] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:45:19] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:45:19] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:45:29] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:45:29] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:45:39] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:45:39] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:45:49] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:45:49] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:45:59] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:45:59] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:46:09] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:46:09] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:46:19] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:46:19] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:46:29] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:46:29] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:46:39] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:46:39] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:46:49] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:46:49] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:46:59] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:46:59] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:47:09] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:47:09] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:47:19] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:47:19] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:47:29] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:47:29] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:47:40] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:47:40] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:47:50] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:47:50] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:48:00] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:48:00] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:48:10] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:48:10] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:48:20] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:48:20] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:48:30] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:48:30] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:48:40] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:48:40] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:48:50] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:48:50] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:49:00] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:49:00] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:49:11] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:49:11] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:49:22] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:49:22] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:49:33] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:49:33] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:49:44] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:49:44] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:49:55] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:49:55] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:50:06] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:50:06] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:50:17] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:50:17] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:50:28] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:50:28] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:50:39] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:50:39] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:50:50] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:50:50] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:51:00] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:51:00] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:51:11] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:51:11] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:51:22] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:51:22] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:51:33] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:51:33] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:51:43] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:51:43] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:51:53] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:51:53] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:52:04] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:52:04] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:52:14] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:52:14] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:52:24] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:52:24] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:52:34] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:52:34] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:52:44] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:52:44] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:52:54] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:52:54] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:53:04] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:53:04] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:53:14] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:53:14] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:53:24] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:53:24] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:53:34] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:53:34] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:53:44] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:53:44] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:53:54] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:53:54] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:54:04] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:54:04] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:54:14] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:54:14] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:54:25] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:54:25] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:54:35] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:54:35] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:54:45] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:54:45] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:54:55] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:54:55] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:55:05] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:55:05] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:55:15] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:55:15] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:55:25] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:55:25] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:55:35] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:55:35] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:55:47] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[07:55:47] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:55:47] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[07:55:47] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:55:57] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:55:57] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:56:08] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:56:08] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:56:19] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:56:19] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:56:30] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:56:30] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[07:56:41] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async VKBot.poll (/root/groupbot3/dist/vkbot.js:72:35)
[07:56:41] Error: {
  error_code: 10,
  error_msg: 'Internal server error: could not check access_token now, check later. (2)',
  request_params: [Array]
}
[08:28:13] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[08:28:13] Error: {
  error_code: 901,
  error_msg: "Can't send messages for users without permission",
  request_params: [Array]
}
[08:28:13] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[08:28:13] Error: {
  error_code: 901,
  error_msg: "Can't send messages for users without permission",
  request_params: [Array]
}
[08:59:49] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[08:59:49] Error: {
  error_code: 901,
  error_msg: "Can't send messages for users without permission",
  request_params: [Array]
}
[08:59:49] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[08:59:49] Error: {
  error_code: 901,
  error_msg: "Can't send messages for users without permission",
  request_params: [Array]
}
[09:31:24] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[09:31:24] Error: {
  error_code: 901,
  error_msg: "Can't send messages for users without permission",
  request_params: [Array]
}
[09:31:25] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[09:31:25] Error: {
  error_code: 901,
  error_msg: "Can't send messages for users without permission",
  request_params: [Array]
}
[10:03:03] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[10:03:03] Error: {
  error_code: 901,
  error_msg: "Can't send messages for users without permission",
  request_params: [Array]
}
[10:03:04] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[10:03:04] Error: {
  error_code: 901,
  error_msg: "Can't send messages for users without permission",
  request_params: [Array]
}
[10:34:40] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[10:34:40] Error: {
  error_code: 901,
  error_msg: "Can't send messages for users without permission",
  request_params: [Array]
}
[10:34:41] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[10:34:41] Error: {
  error_code: 901,
  error_msg: "Can't send messages for users without permission",
  request_params: [Array]
}
[11:06:23] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[11:06:23] Error: {
  error_code: 901,
  error_msg: "Can't send messages for users without permission",
  request_params: [Array]
}
[11:06:24] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[11:06:24] Error: {
  error_code: 901,
  error_msg: "Can't send messages for users without permission",
  request_params: [Array]
}
[11:21:42] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[11:21:42] Error: {
  error_code: 901,
  error_msg: "Can't send messages for users without permission",
  request_params: [Array]
}
[15:12:13] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[15:12:13] Error: {
  error_code: 901,
  error_msg: "Can't send messages for users without permission",
  request_params: [Array]
}
[15:43:51] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[15:43:51] Error: {
  error_code: 901,
  error_msg: "Can't send messages for users without permission",
  request_params: [Array]
}
[16:15:16] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[16:15:16] Error: {
  error_code: 901,
  error_msg: "Can't send messages for users without permission",
  request_params: [Array]
}
[16:46:36] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[16:46:36] Error: {
  error_code: 901,
  error_msg: "Can't send messages for users without permission",
  request_params: [Array]
}
[17:17:51] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[17:17:51] Error: {
  error_code: 901,
  error_msg: "Can't send messages for users without permission",
  request_params: [Array]
}
[17:49:05] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[17:49:05] Error: {
  error_code: 901,
  error_msg: "Can't send messages for users without permission",
  request_params: [Array]
}
[18:20:14] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[18:20:14] Error: {
  error_code: 901,
  error_msg: "Can't send messages for users without permission",
  request_params: [Array]
}
[18:51:22] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[18:51:22] Error: {
  error_code: 901,
  error_msg: "Can't send messages for users without permission",
  request_params: [Array]
}
[19:22:30] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[19:22:30] Error: {
  error_code: 901,
  error_msg: "Can't send messages for users without permission",
  request_params: [Array]
}
[19:53:39] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[19:53:39] Error: {
  error_code: 901,
  error_msg: "Can't send messages for users without permission",
  request_params: [Array]
}
[20:24:48] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[20:24:48] Error: {
  error_code: 901,
  error_msg: "Can't send messages for users without permission",
  request_params: [Array]
}
[20:55:59] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[20:55:59] Error: {
  error_code: 901,
  error_msg: "Can't send messages for users without permission",
  request_params: [Array]
}
[21:27:11] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[21:27:11] Error: {
  error_code: 901,
  error_msg: "Can't send messages for users without permission",
  request_params: [Array]
}
[21:58:24] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[21:58:24] Error: {
  error_code: 901,
  error_msg: "Can't send messages for users without permission",
  request_params: [Array]
}
[22:29:37] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[22:29:37] Error: {
  error_code: 901,
  error_msg: "Can't send messages for users without permission",
  request_params: [Array]
}
[23:00:51] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[23:00:51] Error: {
  error_code: 901,
  error_msg: "Can't send messages for users without permission",
  request_params: [Array]
}
[23:32:08] Error: Error: An error has occurred:
    at VKBot.request (/root/groupbot3/dist/vkbot.js:54:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[23:32:08] Error: {
  error_code: 901,
  error_msg: "Can't send messages for users without permission",
  request_params: [Array]
}
